name: benchmark
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - autopep8=1.6.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - colorama=0.4.4
  - curl=7.82.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - flake8=4.0.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - giflib=5.2.1
  - git=2.34.1
  - glib=2.69.1
  - hyperopt
  - icu=58.2
  - imbalanced-learn=0.9.1
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libffi=3.3
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mccabe=0.7.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.37
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pyflakes=2.4.0
  - pygments=2.11.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytorch=1.12.1
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - transforms3d=0.4.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xgboost
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - actipy==1.1.0
prefix: